### ISSUE TITLE
Turning `disas-bench` into an independent project

### ISSUE THREAD

**Issue by athre0z** [athre0z/disas-bench#4]
Hi there!

@iximeow 
@wtfsck

What do y'all think about turning `disas-bench` into an independent project, with all three of us as maintainers? I noticed that [`icedland/disas-bench`](https://github.com/icedland/disas-bench) is ahead by 29 commits now, with many great improvements that would be great to have upstream. Aside from me being afraid of forks drifting away from each other, I feel that for neutrality, this app shouldn't be governed by a single maintainer of a disassembler lib.

### Proposal

- Create an organization `disas-bench`
- Add all three of us as administrators 
- Move this repository into the newly created organization
- Merge changes from `icedland/disas-bench`
- Make `master`/`main` a protected branch, requiring a review from at least one other maintainer

I'll admit that creating an organization for this feels a bit overkill -- alternatively, I can just add you two as maintainers to this repo on my account. I'm pinging you folks for this initial decision specifically because you both have made major contributions here. Later, we could also add other maintainers of other disassembler libraries to the project, if they are interested.

What do you think?

**Comment by wtfsck** [comment]
I don't think that's necessary. Feel free to cherry-pick the latest stuff: updated graph gen code (dark mode), build script, lto and clang support, and two other libs.

**Comment by iximeow** [comment]
likewise, i think an organization for this would be a bit much. that said, i'm happy to be a maintainer and take a look at PRs here.

**Comment by athre0z** [comment]
Alright! I added you as a maintainer ixi! :)
