### ISSUE TITLE
Refresh results in README

### ISSUE THREAD

**Issue by tetsuo-cpp** [athre0z/disas-bench#8]
Since Ghidra Sleigh was added in #7, it'd be good to see those results in the README.

**Comment by wtfsck** [comment]
Could you send a PR?

**Comment by tetsuo-cpp** [comment]
> Could you send a PR?

I don't have the hardware that's used in the benchmark results.

For #7, I was developing on a VM. If you're happy with just any two Linux/MacOS benchmarks, I might be able to ask around and figure something out but if someone has the hardware lying around, that'd be easier.

**Comment by athre0z** [comment]
Note that we're already on it here: https://github.com/athre0z/disas-bench/pull/9

**Comment by tetsuo-cpp** [comment]
> Note that we're already on it here: #9

Neat! Thanks @athre0z and @iximeow.

**Comment by athre0z** [comment]
Done in e94664c350330487ebb7918f7dd1b05636273de7.
